### ISSUE TITLE
ImportError: cannot import name url_encode

### ISSUE THREAD

**Issue by mgerhardy** [biarms/pgadmin4#8]
```
Traceback (most recent call last):
  File "./usr/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py", line 34, in <module>
    import config
  File "/usr/lib/python2.7/site-packages/pgadmin4/config.py", line 29, in <module>
    from pgadmin.utils import env, IS_PY2, IS_WIN, fs_short_path
  File "/usr/lib/python2.7/site-packages/pgadmin4/pgadmin/__init__.py", line 23, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore, current_user
  File "/usr/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/usr/lib/python2.7/site-packages/flask_security/core.py", line 28, in <module>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/usr/lib/python2.7/site-packages/flask_security/forms.py", line 17, in <module>
    from flask_wtf import FlaskForm as BaseForm
  File "/usr/lib/python2.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/usr/lib/python2.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/usr/lib/python2.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/usr/lib/python2.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name url_encode
```

See https://github.com/pallets/werkzeug/issues/1714

I'm not sure whether this is more a pgadmin issue - but currently the image doesn't work for me.

**Comment by Berisan** [comment]
See also thaJeztah/pgadmin4-docker#48

**Comment by biarms** [comment]
@mgerhardy Sorry for answering you only today: I did a configuration mistake on github and I was never notify about it :(.
FYI, I have publish an upgrade to 4.12, which don't have this pb. I let you have a look to confirm it is OK for you (if not too late).

**Comment by mgerhardy** [comment]
This is fixed with the latest version - thanks a lot
